#! /bin/sh

NAME="automated"
DESC="automated_daemon"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"

AUTOMATE_PATH="/opt/automated/"

START_OPTS="--start -d /opt/automated --exec ${AUTOMATE_PATH}start.sh"

case "$1" in
        start)
            echo -n "Starting ${DESC}: "
            start-stop-daemon $START_OPTS >> $LOGFILE
            echo "$NAME."
        ;;
        stop)
	    ${AUTOMATE_PATH}stop.sh
            echo "$NAME."
        ;;
        restart|force-reload)
            echo -n "Restarting $DESC: "
            echo "$NAME."
       ;;
        *)
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|force-reload}" >&2
            exit 1
        ;;
esac

exit 0

